services:
  netdoishop_app:
    build: .
    container_name: netdoishop_app
    restart: unless-stopped
    env_file: .env
    expose:
      - "3005"
    volumes:
      - sales_uploads:/app/public/uploads/sales
    networks:
      - biw_net

networks:
  biw_net:
    external: true

volumes:
  sales_uploads:
