import { NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { prisma } from "@/lib/prisma";
import { ALLOWED_ROLES } from "@/lib/auth";

class InviteInvalidError extends Error {}

// POST /api/users/signup  { token, username, password, name }
// Staff/admin self-registration via a one-time link generated by an admin.
// No cookie is set here — staff sign in afterwards through the normal
// NextAuth /login flow, so this just creates the row.
export async function POST(req: Request) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "bad json" }, { status: 400 });
  }
  const b = body as Record<string, unknown>;

  const token = typeof b.token === "string" ? b.token : "";
  const username = typeof b.username === "string" ? b.username.trim() : "";
  const password = typeof b.password === "string" ? b.password : "";
  const name = typeof b.name === "string" ? b.name.trim() : "";

  if (!token) return NextResponse.json({ error: "bad token" }, { status: 400 });
  if (!username) return NextResponse.json({ error: "bad username" }, { status: 400 });
  if (password.length < 6) {
    return NextResponse.json({ error: "password too short" }, { status: 400 });
  }

  const passwordHash = await bcrypt.hash(password, 10);

  try {
    const user = await prisma.$transaction(async (tx) => {
      const invite = await tx.accountInvite.findUnique({ where: { token } });
      if (
        !invite ||
        invite.used ||
        invite.expiresAt.getTime() <= Date.now() ||
        !ALLOWED_ROLES.includes(invite.intendedRole as (typeof ALLOWED_ROLES)[number])
      ) {
        throw new InviteInvalidError();
      }

      const claimed = await tx.accountInvite.updateMany({
        where: { token, used: false, expiresAt: { gt: new Date() } },
        data: { used: true, usedAt: new Date() },
      });
      if (claimed.count !== 1) throw new InviteInvalidError();

      return tx.user.create({
        data: { username, passwordHash, name, role: invite.intendedRole },
      });
    });

    return NextResponse.json({ ok: true, username: user.username }, { status: 201 });
  } catch (e) {
    if (e instanceof InviteInvalidError) {
      return NextResponse.json({ error: "invite invalid" }, { status: 410 });
    }
    return NextResponse.json({ error: "username taken" }, { status: 400 });
  }
}
